def gen_even_numbers():
    """
    Generator that produces an infinite sequence of even numbers.
    """
    number = 0
    while True:
        number += 2
        yield number

def save_first_100_numbers(filename):
    """
    Saves the first 100 even numbers generated by gen_even_numbers to a file.

    :param filename: Name of the file to save the numbers
    """
    result = []
    for number in gen_even_numbers():
        if len(result) == 100:
            break
        result.append(number)

    with open(filename, "w", encoding="utf-8") as f:
        for number in result:
            f.write(str(number) + ", ")


save_first_100_numbers("result_simple.txt")